-- Insert Services for VeyraTech
INSERT INTO services (id, name, slug, description, problem, solution, deliverables, business_outcomes, faq, seo_title, seo_description, display_order, published, created_at, updated_at) 
VALUES
(
  uuid_generate_v4(),
  'Technology Strategy & Planning',
  'technology-strategy',
  'Strategic technology planning that aligns with your business objectives and creates competitive advantage.',
  E'["Unclear technology direction and priorities", "Technology investments not delivering expected ROI", "Difficulty evaluating emerging technologies like AI", "Technology decisions made in isolation from business strategy", "Competing priorities and limited resources"]',
  E'["Comprehensive technology assessment of current state", "Clear technology roadmap aligned with business goals", "Prioritized initiatives with expected business impact", "Technology investment framework and governance", "Vendor evaluation and selection guidance"]',
  E'["Technology Strategy Document", "3-Year Technology Roadmap", "Investment Priorities & Budget Recommendations", "Technology Governance Framework", "Vendor Evaluation Criteria", "Risk Assessment & Mitigation Plans"]',
  E'["Clear technology direction aligned with business goals", "Optimized technology investments with measurable ROI", "Reduced technology risk and vendor lock-in", "Faster, more confident technology decisions", "Competitive advantage through strategic technology use"]',
  E'[{"question":"How long does a technology strategy engagement take?","answer":"Typically 6-8 weeks, depending on organization size and complexity. We work efficiently to deliver actionable insights quickly."},{"question":"Do we need a large IT team to implement the strategy?","answer":"No. We design strategies that are realistic for your current resources and include phased implementation plans."},{"question":"How do you ensure the strategy aligns with our business goals?","answer":"We start by understanding your business objectives, challenges, and constraints before making any technology recommendations."}]',
  'Technology Strategy & Planning | VeyraTech',
  'Strategic technology planning aligned with business objectives. Get clear direction for technology investments and initiatives.',
  1,
  true,
  NOW(),
  NOW()
),
(
  uuid_generate_v4(),
  'AI Consulting & Implementation',
  'ai-consulting',
  'Practical AI consulting focused on real business problems and measurable outcomes, not hype.',
  E'["Uncertainty about where AI can actually help", "Difficulty separating AI hype from reality", "Concerns about cost, complexity, and risk", "Lack of AI expertise and implementation experience", "Unclear ROI and business case for AI initiatives"]',
  E'["AI opportunity assessment for your specific business", "Use case identification with ROI estimates", "Proof of concept development and testing", "AI implementation roadmap and governance", "Team training and capability building"]',
  E'["AI Opportunity Assessment Report", "Prioritized AI Use Cases with ROI Analysis", "Proof of Concept (POC) Results", "AI Implementation Roadmap", "AI Governance Framework", "Training Materials & Documentation"]',
  E'["Clear understanding of where AI adds value", "Reduced risk through tested proof of concepts", "Faster time to AI-driven business outcomes", "Internal AI capability and knowledge", "Competitive advantage through intelligent automation"]',
  E'[{"question":"Do we need a data science team to use AI?","answer":"Not necessarily. We help you leverage AI tools and platforms appropriate for your resources and maturity level."},{"question":"How do you ensure AI recommendations are practical?","answer":"We focus on proven AI applications with clear ROI, not experimental or bleeding-edge approaches."},{"question":"What if our data is not ready for AI?","answer":"We assess your data readiness and include data preparation in our recommendations when needed."}]',
  'AI Consulting & Implementation | VeyraTech',
  'Practical AI consulting focused on business outcomes. Identify AI opportunities and implement solutions that deliver ROI.',
  2,
  true,
  NOW(),
  NOW()
),
(
  uuid_generate_v4(),
  'Business Process Automation',
  'business-automation',
  'Intelligent automation that eliminates repetitive work and improves operational efficiency.',
  E'["Manual, repetitive tasks consuming valuable time", "Human error in routine processes", "Inconsistent process execution across teams", "Difficulty scaling operations without adding headcount", "Limited visibility into process performance"]',
  E'["Process assessment and automation opportunity identification", "Workflow design and optimization", "Automation tool selection and implementation", "Integration with existing systems", "Change management and user adoption support"]',
  E'["Process Assessment Report", "Automation Roadmap", "Workflow Designs & Documentation", "Implemented Automation Solutions", "User Training & Support Materials", "Performance Metrics & Dashboards"]',
  E'["Significant time savings on repetitive tasks", "Reduced errors and improved quality", "Consistent process execution", "Ability to scale without proportional headcount increase", "Real-time visibility into operations"]',
  E'[{"question":"Which processes should we automate first?","answer":"We help you prioritize based on impact, feasibility, and ROI. Usually high-volume, rule-based processes offer the quickest wins."},{"question":"Will automation eliminate jobs?","answer":"Most automation frees people from repetitive work to focus on higher-value activities. We help manage this transition."},{"question":"How complex is it to maintain automation?","answer":"We design automation for your team to maintain, with documentation and training included."}]',
  'Business Process Automation | VeyraTech',
  'Intelligent automation that eliminates repetitive work. Improve efficiency and reduce errors with smart process automation.',
  3,
  true,
  NOW(),
  NOW()
),
(
  uuid_generate_v4(),
  'Digital Transformation',
  'digital-transformation',
  'Comprehensive digital transformation that modernizes operations and creates new business capabilities.',
  E'["Legacy systems limiting business agility", "Manual processes in a digital world", "Disconnected systems and data silos", "Difficulty meeting changing customer expectations", "Competitive pressure from digital-native companies"]',
  E'["Digital maturity assessment", "Transformation strategy and roadmap", "Technology modernization planning", "Digital capability development", "Change management and stakeholder engagement"]',
  E'["Digital Maturity Assessment", "Transformation Strategy & Roadmap", "Technology Modernization Plan", "Business Case & ROI Analysis", "Change Management Plan", "Implementation Support"]',
  E'["Modern, integrated technology foundation", "Improved customer experience and engagement", "Greater business agility and speed", "New revenue opportunities through digital channels", "Reduced operational costs"]',
  E'[{"question":"How long does digital transformation take?","answer":"It is a journey, not a project. We design phased approaches that deliver value incrementally while building toward long-term vision."},{"question":"Do we need to replace all our systems?","answer":"Not usually. We evaluate what to modernize, what to integrate, and what to replace based on business value and risk."},{"question":"How do you manage organizational change?","answer":"Change management is built into our approach, not an afterthought. We help prepare your organization for new ways of working."}]',
  'Digital Transformation | VeyraTech',
  'Comprehensive digital transformation that modernizes operations. Create new capabilities and competitive advantages.',
  4,
  true,
  NOW(),
  NOW()
),
(
  uuid_generate_v4(),
  'Software & Systems Advisory',
  'software-systems',
  'Expert guidance on software selection, implementation, and optimization.',
  E'["Overwhelming number of software options", "Difficulty evaluating vendor claims", "Implementation failures and cost overruns", "Software not meeting business needs", "Poor integration between systems"]',
  E'["Requirements gathering and analysis", "Vendor evaluation and selection", "Implementation planning and oversight", "Integration architecture design", "Vendor negotiation support"]',
  E'["Requirements Document", "Vendor Evaluation Matrix", "Software Recommendation & Business Case", "Implementation Plan", "Integration Architecture", "Negotiation Support"]',
  E'["Confident software selection decisions", "Reduced implementation risk and cost", "Software that fits business needs", "Better vendor terms and pricing", "Successful software adoption"]',
  E'[{"question":"Do you recommend specific vendors?","answer":"We are vendor-agnostic. Our recommendations are based on your specific requirements and context."},{"question":"Can you help with existing software that is not working well?","answer":"Yes. We assess current software usage and recommend optimization or replacement strategies."},{"question":"Do you handle technical implementation?","answer":"We provide strategic guidance and oversight. We can also recommend implementation partners when needed."}]',
  'Software & Systems Advisory | VeyraTech',
  'Expert software selection and implementation guidance. Make confident decisions and avoid costly mistakes.',
  5,
  true,
  NOW(),
  NOW()
),
(
  uuid_generate_v4(),
  'Technology Advisory Services',
  'technology-advisory',
  'Ongoing technology advisory and fractional CTO services for growing organizations.',
  E'["No dedicated technology leadership", "Technology decisions without strategic context", "Difficulty keeping up with technology changes", "Need for objective technology advice", "Technology challenges slowing business growth"]',
  E'["Fractional CTO/CIO services", "Regular technology advisory sessions", "Strategic technology decision support", "Vendor and partner management", "Technology team guidance and mentoring"]',
  E'["Regular Advisory Sessions", "Technology Decision Recommendations", "Vendor Management Support", "Technology Team Guidance", "Strategic Technology Updates", "On-demand Advisory Access"]',
  E'["Access to senior technology expertise", "Better technology decisions aligned with business", "Reduced technology risk", "Cost-effective alternative to full-time hire", "Technology as competitive advantage"]',
  E'[{"question":"How does fractional CTO service work?","answer":"We provide senior technology leadership on a part-time or retainer basis, tailored to your needs and budget."},{"question":"What is the minimum engagement?","answer":"Typically a 3-month minimum to establish context and deliver value. Most clients engage for 6-12 months or longer."},{"question":"Can you work with our existing IT team?","answer":"Absolutely. We complement and support your internal team, providing strategic guidance and additional expertise."}]',
  'Technology Advisory Services | VeyraTech',
  'Ongoing technology advisory and fractional CTO services. Get expert guidance without full-time executive hire.',
  6,
  true,
  NOW(),
  NOW()
);
