-- Create all enum types if they don't exist
-- Run this in Supabase SQL Editor

DO $$ BEGIN
    CREATE TYPE industry AS ENUM ('REAL_ESTATE', 'CONSTRUCTION', 'LOGISTICS', 'HOSPITALITY', 'PROFESSIONAL_SERVICES', 'GROWING_ENTERPRISES', 'OTHER');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
    CREATE TYPE company_size AS ENUM ('SMALL', 'MEDIUM', 'LARGE', 'ENTERPRISE');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
    CREATE TYPE service_area AS ENUM ('TECHNOLOGY_STRATEGY', 'AI_CONSULTING', 'AUTOMATION', 'DIGITAL_TRANSFORMATION', 'SOFTWARE_SYSTEMS', 'TECHNOLOGY_ADVISORY', 'NOT_SURE');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
    CREATE TYPE consultation_status AS ENUM ('NEW', 'REVIEWING', 'CONTACTED', 'SCHEDULED', 'COMPLETED', 'CANCELLED', 'CONVERTED');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
    CREATE TYPE lead_status AS ENUM ('NEW', 'CONTACTED', 'QUALIFIED', 'CONSULTATION', 'PROPOSAL', 'NEGOTIATION', 'WON', 'LOST', 'NURTURE');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
    CREATE TYPE lead_source AS ENUM ('WEBSITE', 'EMAIL', 'PHONE', 'LINKEDIN', 'REFERRAL', 'EVENT', 'DIRECT_OUTREACH', 'OTHER');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
    CREATE TYPE prospect_status AS ENUM ('NOT_CONTACTED', 'EMAIL_SENT', 'CALL_MADE', 'REPLIED', 'MEETING', 'QUALIFIED', 'FOLLOW_UP', 'NOT_INTERESTED', 'CONVERTED');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
    CREATE TYPE priority AS ENUM ('LOW', 'MEDIUM', 'HIGH', 'URGENT');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
    CREATE TYPE proposal_status AS ENUM ('DRAFT', 'SENT', 'VIEWED', 'ACCEPTED', 'REJECTED', 'EXPIRED');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
    CREATE TYPE project_status AS ENUM ('PLANNING', 'ACTIVE', 'ON_HOLD', 'COMPLETED', 'CANCELLED');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
    CREATE TYPE project_stage AS ENUM ('DISCOVERY', 'ASSESSMENT', 'STRATEGY', 'DESIGN', 'IMPLEMENTATION', 'TESTING', 'DEPLOYMENT', 'OPTIMIZATION');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
    CREATE TYPE assessment_status AS ENUM ('DRAFT', 'IN_REVIEW', 'COMPLETED', 'ARCHIVED');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
    CREATE TYPE assessment_type AS ENUM ('TECHNOLOGY_ASSESSMENT', 'AI_READINESS_ASSESSMENT', 'AUTOMATION_ASSESSMENT', 'DIGITAL_TRANSFORMATION_ASSESSMENT');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
    CREATE TYPE document_type AS ENUM ('PROPOSAL', 'CONTRACT', 'ASSESSMENT', 'REPORT', 'PROJECT_FILE', 'INVOICE', 'CASE_STUDY', 'INTERNAL', 'OTHER');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
    CREATE TYPE insight_status AS ENUM ('DRAFT', 'SCHEDULED', 'PUBLISHED', 'ARCHIVED');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
    CREATE TYPE insight_category AS ENUM ('TECHNOLOGY_STRATEGY', 'ARTIFICIAL_INTELLIGENCE', 'AUTOMATION', 'DIGITAL_TRANSFORMATION', 'BUSINESS_TECHNOLOGY', 'DATA', 'CYBERSECURITY', 'CONSULTING');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
    CREATE TYPE notification_type AS ENUM ('NEW_LEAD', 'NEW_CONTACT', 'NEW_CONSULTATION', 'CONSULTATION_UPDATE', 'PROPOSAL_ACTION', 'PROJECT_DEADLINE', 'NEW_MESSAGE', 'SYSTEM_ALERT');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
    CREATE TYPE audit_action AS ENUM ('ADMIN_LOGIN', 'FAILED_LOGIN', 'LEAD_CREATED', 'LEAD_UPDATED', 'PROSPECT_CREATED', 'PROSPECT_UPDATED', 'CONSULTATION_CREATED', 'CONSULTATION_UPDATED', 'PROPOSAL_CREATED', 'PROPOSAL_SENT', 'PROPOSAL_ACCEPTED', 'PROJECT_CREATED', 'PROJECT_UPDATED', 'DOCUMENT_UPLOADED', 'DOCUMENT_DELETED', 'INSIGHT_PUBLISHED', 'SERVICE_UPDATED', 'SETTINGS_CHANGED');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
    CREATE TYPE admin_status AS ENUM ('ACTIVE', 'INACTIVE');
EXCEPTION WHEN duplicate_object THEN null; END $$;
