// Common enums and types used throughout the application

export enum LeadStatus {
  NEW = "NEW",
  CONTACTED = "CONTACTED",
  QUALIFIED = "QUALIFIED",
  CONSULTATION = "CONSULTATION",
  PROPOSAL = "PROPOSAL",
  NEGOTIATION = "NEGOTIATION",
  WON = "WON",
  LOST = "LOST",
  NURTURE = "NURTURE",
}

export enum LeadSource {
  WEBSITE = "WEBSITE",
  EMAIL = "EMAIL",
  PHONE = "PHONE",
  LINKEDIN = "LINKEDIN",
  REFERRAL = "REFERRAL",
  EVENT = "EVENT",
  DIRECT_OUTREACH = "DIRECT_OUTREACH",
  OTHER = "OTHER",
}

export enum ProspectStatus {
  NOT_CONTACTED = "NOT_CONTACTED",
  EMAIL_SENT = "EMAIL_SENT",
  CALL_MADE = "CALL_MADE",
  REPLIED = "REPLIED",
  MEETING = "MEETING",
  QUALIFIED = "QUALIFIED",
  FOLLOW_UP = "FOLLOW_UP",
  NOT_INTERESTED = "NOT_INTERESTED",
  CONVERTED = "CONVERTED",
}

export enum ConsultationStatus {
  NEW = "NEW",
  REVIEWING = "REVIEWING",
  CONTACTED = "CONTACTED",
  SCHEDULED = "SCHEDULED",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
  CONVERTED = "CONVERTED",
  NO_SHOW = "NO_SHOW",
}

export enum ConsultationType {
  AI_ADOPTION = "AI_ADOPTION",
  AI_STRATEGY = "AI_STRATEGY",
  BUSINESS_AUTOMATION = "BUSINESS_AUTOMATION",
  DIGITAL_TRANSFORMATION = "DIGITAL_TRANSFORMATION",
  TECHNOLOGY_STRATEGY = "TECHNOLOGY_STRATEGY",
  SOFTWARE_DEVELOPMENT = "SOFTWARE_DEVELOPMENT",
  TECHNOLOGY_AUDIT = "TECHNOLOGY_AUDIT",
  DATA_ANALYTICS = "DATA_ANALYTICS",
  CYBERSECURITY = "CYBERSECURITY",
  BUSINESS_PROCESS_OPTIMIZATION = "BUSINESS_PROCESS_OPTIMIZATION",
  CUSTOM_SOLUTION = "CUSTOM_SOLUTION",
  OTHER = "OTHER",
}

export enum MeetingType {
  GOOGLE_MEET = "GOOGLE_MEET",
  PHONE = "PHONE",
  IN_PERSON = "IN_PERSON",
}

export enum ConsultationOutcome {
  PROPOSAL_REQUIRED = "PROPOSAL_REQUIRED",
  FOLLOW_UP_MEETING = "FOLLOW_UP_MEETING",
  ASSESSMENT_REQUIRED = "ASSESSMENT_REQUIRED",
  SEND_QUOTATION = "SEND_QUOTATION",
  IMPLEMENTATION_OPPORTUNITY = "IMPLEMENTATION_OPPORTUNITY",
  CLIENT_NOT_READY = "CLIENT_NOT_READY",
  NOT_QUALIFIED = "NOT_QUALIFIED",
  COMPLETED = "COMPLETED",
  OTHER = "OTHER",
}

export enum ReminderType {
  REMINDER_24H = "REMINDER_24H",
  REMINDER_1H = "REMINDER_1H",
  REMINDER_10M = "REMINDER_10M",
}

export enum ProposalStatus {
  DRAFT = "DRAFT",
  SENT = "SENT",
  VIEWED = "VIEWED",
  ACCEPTED = "ACCEPTED",
  REJECTED = "REJECTED",
  EXPIRED = "EXPIRED",
}

export enum ProjectStatus {
  PLANNING = "PLANNING",
  ACTIVE = "ACTIVE",
  ON_HOLD = "ON_HOLD",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
}

export enum ProjectStage {
  DISCOVERY = "DISCOVERY",
  ASSESSMENT = "ASSESSMENT",
  STRATEGY = "STRATEGY",
  DESIGN = "DESIGN",
  IMPLEMENTATION = "IMPLEMENTATION",
  TESTING = "TESTING",
  DEPLOYMENT = "DEPLOYMENT",
  OPTIMIZATION = "OPTIMIZATION",
}

export enum AssessmentStatus {
  DRAFT = "DRAFT",
  IN_REVIEW = "IN_REVIEW",
  COMPLETED = "COMPLETED",
  ARCHIVED = "ARCHIVED",
}

export enum DocumentType {
  PROPOSAL = "PROPOSAL",
  CONTRACT = "CONTRACT",
  ASSESSMENT = "ASSESSMENT",
  REPORT = "REPORT",
  PROJECT_FILE = "PROJECT_FILE",
  INVOICE = "INVOICE",
  CASE_STUDY = "CASE_STUDY",
  INTERNAL = "INTERNAL",
  OTHER = "OTHER",
}

export enum InsightStatus {
  DRAFT = "DRAFT",
  SCHEDULED = "SCHEDULED",
  PUBLISHED = "PUBLISHED",
  ARCHIVED = "ARCHIVED",
}

export enum InsightCategory {
  TECHNOLOGY_STRATEGY = "TECHNOLOGY_STRATEGY",
  ARTIFICIAL_INTELLIGENCE = "ARTIFICIAL_INTELLIGENCE",
  AUTOMATION = "AUTOMATION",
  DIGITAL_TRANSFORMATION = "DIGITAL_TRANSFORMATION",
  BUSINESS_TECHNOLOGY = "BUSINESS_TECHNOLOGY",
  DATA = "DATA",
  CYBERSECURITY = "CYBERSECURITY",
  CONSULTING = "CONSULTING",
}

export enum AdminStatus {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
}

export enum Priority {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
  URGENT = "URGENT",
}

export enum Industry {
  REAL_ESTATE = "REAL_ESTATE",
  CONSTRUCTION = "CONSTRUCTION",
  FINANCE = "FINANCE",
  BANKING = "BANKING",
  INSURANCE = "INSURANCE",
  RETAIL = "RETAIL",
  HEALTHCARE = "HEALTHCARE",
  HOSPITALITY = "HOSPITALITY",
  EDUCATION = "EDUCATION",
  MANUFACTURING = "MANUFACTURING",
  LOGISTICS_TRANSPORT = "LOGISTICS_TRANSPORT",
  AGRICULTURE = "AGRICULTURE",
  PROFESSIONAL_SERVICES = "PROFESSIONAL_SERVICES",
  TECHNOLOGY = "TECHNOLOGY",
  MEDIA_ENTERTAINMENT = "MEDIA_ENTERTAINMENT",
  ECOMMERCE = "ECOMMERCE",
  GOVERNMENT_NGO = "GOVERNMENT_NGO",
  OTHER = "OTHER",
}

export enum CompanySize {
  SIZE_1_10 = "SIZE_1_10",
  SIZE_11_50 = "SIZE_11_50",
  SIZE_51_100 = "SIZE_51_100",
  SIZE_101_500 = "SIZE_101_500",
  SIZE_500_PLUS = "SIZE_500_PLUS",
}

export enum ServiceArea {
  TECHNOLOGY_STRATEGY = "TECHNOLOGY_STRATEGY",
  AI_CONSULTING = "AI_CONSULTING",
  AUTOMATION = "AUTOMATION",
  DIGITAL_TRANSFORMATION = "DIGITAL_TRANSFORMATION",
  SOFTWARE_SYSTEMS = "SOFTWARE_SYSTEMS",
  TECHNOLOGY_ADVISORY = "TECHNOLOGY_ADVISORY",
  NOT_SURE = "NOT_SURE",
}

export enum NotificationType {
  NEW_LEAD = "NEW_LEAD",
  NEW_CONTACT = "NEW_CONTACT",
  NEW_CONSULTATION = "NEW_CONSULTATION",
  CONSULTATION_UPDATE = "CONSULTATION_UPDATE",
  PROPOSAL_ACTION = "PROPOSAL_ACTION",
  PROJECT_DEADLINE = "PROJECT_DEADLINE",
  NEW_MESSAGE = "NEW_MESSAGE",
  SYSTEM_ALERT = "SYSTEM_ALERT",
}

export enum AuditAction {
  ADMIN_LOGIN = "ADMIN_LOGIN",
  FAILED_LOGIN = "FAILED_LOGIN",
  LEAD_CREATED = "LEAD_CREATED",
  LEAD_UPDATED = "LEAD_UPDATED",
  PROPOSAL_CREATED = "PROPOSAL_CREATED",
  PROPOSAL_SENT = "PROPOSAL_SENT",
  PROPOSAL_ACCEPTED = "PROPOSAL_ACCEPTED",
  PROJECT_CREATED = "PROJECT_CREATED",
  PROJECT_UPDATED = "PROJECT_UPDATED",
  DOCUMENT_UPLOADED = "DOCUMENT_UPLOADED",
  DOCUMENT_DELETED = "DOCUMENT_DELETED",
  INSIGHT_PUBLISHED = "INSIGHT_PUBLISHED",
  SERVICE_UPDATED = "SERVICE_UPDATED",
  SETTINGS_CHANGED = "SETTINGS_CHANGED",
}

// API Response Types
export interface ApiResponse<T = any> {
  success: boolean;
  data?: T;
  error?: string;
  message?: string;
}

export interface PaginatedResponse<T> {
  data: T[];
  total: number;
  page: number;
  pageSize: number;
  totalPages: number;
}

export interface DashboardStats {
  totalLeads: number;
  newLeads: number;
  qualifiedLeads: number;
  upcomingConsultations: number;
  pendingProposals: number;
  activeProjects: number;
  completedProjects: number;
  conversionRate: number;
}
